SKILL_CATALOG = {
    "python",
    "java",
    "javascript",
    "typescript",
    "react",
    "next.js",
    "vite",
    "node.js",
    "express",
    "nestjs",
    "fastapi",
    "django",
    "flask",
    "sql",
    "postgresql",
    "mysql",
    "mongodb",
    "redis",
    "docker",
    "kubernetes",
    "aws",
    "azure",
    "gcp",
    "terraform",
    "ansible",
    "linux",
    "bash",
    "graphql",
    "rest api",
    "microservices",
    "event-driven architecture",
    "serverless",
    "ci/cd",
    "github actions",
    "gitlab ci",
    "jenkins",
    "unit testing",
    "integration testing",
    "pytest",
    "jest",
    "cypress",
    "playwright",
    "tailwind css",
    "framer motion",
    "figma",
    "recharts",
    "html",
    "css",
    "sass",
    "bootstrap",
    "material ui",
    "chakra ui",
    "redux",
    "zustand",
    "react query",
    "tanstack query",
    "axios",
    "pandas",
    "numpy",
    "scikit-learn",
    "tensorflow",
    "pytorch",
    "machine learning",
    "deep learning",
    "nlp",
    "openai api",
    "langchain",
    "llmops",
    "prompt engineering",
    "data analysis",
    "data visualization",
    "power bi",
    "tableau",
    "airflow",
    "spark",
    "hadoop",
    "dbt",
    "snowflake",
    "bigquery",
    "product management",
    "agile",
    "scrum",
    "stakeholder management",
    "a/b testing",
    "seo",
    "sem",
    "copywriting",
    "salesforce",
    "hubspot",
    "customer success",
    "project management",
    "jira",
    "notion",
    "communication",
    "leadership",
    "mentoring",
    "system design",
    "problem solving",
    "critical thinking",
    "data structures",
    "algorithms",
    "oauth",
    "jwt",
    "authentication",
    "authorization",
    "spacy",
    "sentence-transformers",
    "pymupdf",
    "python-docx",
    "postgres",
    "saas",
    "startup",
    "analytics",
    "etl",
    "customer research",
    "mobile development",
    "react native",
    "swift",
    "kotlin",
}
