const USER_ROLES = {
  CLIENT: "CLIENT",
  FREELANCER: "FREELANCER"
};

const JOB_STATUSES = {
  OPEN: "OPEN",
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED"
};

const BID_STATUSES = {
  PENDING: "PENDING",
  ACCEPTED: "ACCEPTED",
  REJECTED: "REJECTED"
};

const ACTIVE_BID_STATUSES = [BID_STATUSES.PENDING, BID_STATUSES.ACCEPTED];
const MAX_ACTIVE_BIDS = 5;

module.exports = {
  USER_ROLES,
  JOB_STATUSES,
  BID_STATUSES,
  ACTIVE_BID_STATUSES,
  MAX_ACTIVE_BIDS
};
